import Foundation

struct StructuredReport: Codable, Identifiable, Hashable {
    /// Sentinel string used in `patientSummary` to flag reports that
    /// were short-circuited because the scanned content didn't look
    /// like a lab report at all. Surfaced to the UI via
    /// `wasRejectedAsNonHealth` so ScanView can show an alert popup
    /// instead of pushing into the (empty) DashboardView.
    static let nonHealthRejectionMarker = "__LOCALABS_NON_HEALTH_REJECTED__"

    var id: UUID
    var timestamp: Date
    /// Short title generated by the model and shown in the History
    /// row + report header. Default empty for older reports that
    /// pre-date the feature; `displayTitle` falls back to a date-
    /// based label in that case so the UI stays consistent.
    /// Editable via the History row's Rename action.
    var title: String
    var patientSummary: String
    var doctorQuestions: String
    var dietaryAdvice: String
    var medicalGlossary: String
    var medicationNotes: String
    var rawText: String
    var imagePath: String?
    /// Additional page filenames for multi-page scans (PDFs or multiple
    /// photos). The first page's path stays in `imagePath` so existing
    /// saved reports decode unchanged.
    var additionalPagePaths: [String]?

    /// True when the analysis pipeline refused this scan because it
    /// didn't contain any lab values, units, or medical vocabulary.
    /// Drives the "No health content detected" popup in ScanView.
    /// Checked via a marker in `patientSummary` so we don't have to
    /// change the Codable surface (older saved reports stay decodable).
    var wasRejectedAsNonHealth: Bool {
        patientSummary.contains(Self.nonHealthRejectionMarker)
    }

    init(
        id: UUID = UUID(),
        timestamp: Date = Date(),
        title: String = "",
        patientSummary: String = "",
        doctorQuestions: String = "",
        dietaryAdvice: String = "",
        medicalGlossary: String = "",
        medicationNotes: String = "",
        rawText: String = "",
        imagePath: String? = nil,
        additionalPagePaths: [String]? = nil
    ) {
        self.id = id
        self.timestamp = timestamp
        self.title = title
        self.patientSummary = patientSummary
        self.doctorQuestions = doctorQuestions
        self.dietaryAdvice = dietaryAdvice
        self.medicalGlossary = medicalGlossary
        self.medicationNotes = medicationNotes
        self.rawText = rawText
        self.imagePath = imagePath
        self.additionalPagePaths = additionalPagePaths
    }

    /// Title shown in History rows + the Dashboard header. Uses the
    /// LLM-generated `title` when present, falls back to a date-based
    /// label so reports created before this field existed still read
    /// well in the list.
    var displayTitle: String {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty { return trimmed }
        let formatter = DateFormatter()
        formatter.dateFormat = "MMMM d 'Lab Report'"
        return formatter.string(from: timestamp)
    }

    var imageURL: URL? {
        guard let imagePath else { return nil }
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("scans").appendingPathComponent(imagePath)
    }

    /// True when the report's AI generation didn't produce a normal
    /// 5-section output. Detected by checking whether the patient summary
    /// matches our specific failure / cancellation messages OR every
    /// section is empty despite OCR text being present. Used by the
    /// dashboard to surface a "Resume Analysis" call-to-action.
    var isIncomplete: Bool {
        let hasOCR = !rawText.isEmpty
        // The Localabs prompt instructs the model to always produce
        // all five sections in order. Any missing section overwhelmingly
        // means generation was interrupted mid-stream — pause, app
        // backgrounded, or n_ctx overflow. A legit report on any
        // scanned lab panel produces at least placeholder text for
        // every section (the AI will say "Not applicable" rather than
        // emit nothing). So "any section empty" is the most reliable
        // truncation signal we have without adding an explicit flag.
        let anySectionEmpty = patientSummary.isEmpty
            || doctorQuestions.isEmpty
            || dietaryAdvice.isEmpty
            || medicalGlossary.isEmpty
            || medicationNotes.isEmpty
        let hasFailureMarker = patientSummary.contains("interrupted")
            || patientSummary.contains("didn't complete")
            || patientSummary.contains("Analysis was")
            || patientSummary.contains("Paused before")
            || patientSummary.contains("Failed to extract")
        return hasOCR && (anySectionEmpty || hasFailureMarker)
    }

    /// All page image URLs in document order. Empty if the report has no
    /// saved scans (e.g., weekly Apple Health review). Multi-page reports
    /// have one URL per page in chronological scan order.
    var allImageURLs: [URL] {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let scansDir = docs.appendingPathComponent("scans")
        var urls: [URL] = []
        if let imagePath {
            urls.append(scansDir.appendingPathComponent(imagePath))
        }
        if let extras = additionalPagePaths {
            urls.append(contentsOf: extras.map { scansDir.appendingPathComponent($0) })
        }
        return urls
    }

    static func parse(from rawText: String) -> StructuredReport {
        // Pull the model-generated title (if any) out of the leading
        // `[TITLE: "..."]` marker. We do this first so the title
        // doesn't end up appended to PATIENT SUMMARY. The marker
        // pattern is forgiving on whitespace and quote style so
        // small-model drift doesn't break it.
        var extractedTitle: String = ""
        var workingText = rawText
        let titlePattern = #"\[\s*TITLE\s*:\s*[\"']([^\"'\]]+)[\"']\s*\]"#
        if let regex = try? NSRegularExpression(pattern: titlePattern, options: []) {
            let nsRange = NSRange(rawText.startIndex..., in: rawText)
            if let match = regex.firstMatch(in: rawText, range: nsRange),
               match.numberOfRanges >= 2,
               let captureRange = Range(match.range(at: 1), in: rawText) {
                extractedTitle = String(rawText[captureRange])
                    .trimmingCharacters(in: .whitespacesAndNewlines)
            }
            // Strip every TITLE marker from the section-parsing input so
            // the title doesn't get folded into PATIENT SUMMARY.
            workingText = regex.stringByReplacingMatches(
                in: rawText,
                options: [],
                range: nsRange,
                withTemplate: ""
            ).trimmingCharacters(in: .whitespacesAndNewlines)
        }

        let headers: [(key: String, patterns: [String])] = [
            ("patientSummary",   ["PATIENT SUMMARY"]),
            ("doctorQuestions",  ["QUESTIONS FOR YOUR DOCTOR", "QUESTIONS FOR THE DOCTOR"]),
            ("dietaryAdvice",    ["TARGETED DIETARY ADVICE", "DIETARY ADVICE"]),
            ("medicalGlossary",  ["MEDICAL GLOSSARY", "GLOSSARY"]),
            ("medicationNotes",  ["MEDICATION NOTES", "MEDICATIONS"]),
        ]

        var sections: [String: String] = [:]
        let lines = workingText.components(separatedBy: .newlines)
        var currentKey: String?
        var buffer: [String] = []

        func flush() {
            if let key = currentKey {
                let value = buffer.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
                sections[key] = value
            }
            buffer.removeAll(keepingCapacity: true)
        }

        for line in lines {
            let stripped = line.trimmingCharacters(in: .whitespaces)
                .replacingOccurrences(of: "*", with: "")
                .replacingOccurrences(of: "#", with: "")
                .trimmingCharacters(in: .whitespaces)
            let upper = stripped.uppercased()

            var matchedKey: String?
            for header in headers {
                for pattern in header.patterns {
                    let withoutNumbering = upper
                        .replacingOccurrences(
                            of: #"^\s*\d+[\.\)]\s*"#,
                            with: "",
                            options: .regularExpression
                        )
                    if withoutNumbering.hasPrefix(pattern) {
                        matchedKey = header.key
                        break
                    }
                }
                if matchedKey != nil { break }
            }

            if let key = matchedKey {
                flush()
                currentKey = key
            } else {
                buffer.append(line)
            }
        }
        flush()

        return StructuredReport(
            title: extractedTitle,
            patientSummary: sections["patientSummary"] ?? workingText.trimmingCharacters(in: .whitespacesAndNewlines),
            doctorQuestions: sections["doctorQuestions"] ?? "",
            dietaryAdvice: sections["dietaryAdvice"] ?? "",
            medicalGlossary: sections["medicalGlossary"] ?? "",
            medicationNotes: sections["medicationNotes"] ?? "",
            rawText: rawText
        )
    }
}
